const specializations: string[] = [
    'Orthopedics',
    'Bone',
    'Joint',
    'Arthritis',
    'Spine',
    'Injury',
    'Trauma Surgeon',
    'Neurology',
    'Brain',
    'Nerve',
    'Spine',
    'Medicine',
    'Stroke',
    'Headache',
    'Migraine',
    'Kidneys',
    'Bladder',
    'Ureters',
    'Prostate',
    'Laser',
    'Laparoscopic surgery',
    'Urology',
    'Cardiology',
    'Medicine',
    'Heart',
    'Medicine',
    'Diabetes',
    'Eye',
    'Pediatric',
    'Ophthalmologist',
    'Kidney',
    'Nephrology',
    'Skin',
    'Sex',
    'Allergy',
    'Dermatology',
    'Venereology',
    'Oral',
    'Dental',
    'Maxillofacial',
    'Dental',
    'Dentistry',
    'Orthodontics',
    'Dental',
    'Medicine',
    'Gastrointentine',
    'Liver',
    'Pancreas',
    'Medicine',
    'Cardiology',
    'Heart',
    'Medicine',
    'Diabetes',
    'Medicine',
    'Gastroliver',
    'Rheumatology',
    'Hormone',
    'Diabetes',
    'Nephrology',
    'Neuromedicine',
    'Neurology',
    'Medicine',
    'Brain',
    'Nerve',
    'Headache',
    'Migraine',
    'Stroke',
    'Prostate',
    'Male Organs',
    'Urology',
    'Kidney',
    'Ureter',
    'Bladder',
    'Prostate',
    'Laparoscopic',
    'Infertility',
    'Laparoscopic',
    'Gynecology',
    'Obstetrics',
    'Joint',
    'Arthritis',
    'Trauma',
    'Heart',
    'Cardiology',
    'Medicine',
    'Chest',
    'Heart',
    'Dental Implant',
    'Invisalign',
    'Dental Braces',
    'Smile Design',
    'TM Joint Disorder',
    'Tooth Whitening',
    'Root Canal',
    'Dental Jewelry',
    'Cleft Lip',
    'Palate Surgery',
    'Tooth Extraction',
    'Oral',
    'Cosmetic Filling',
    'Dental Bridge',
    'Internal Medicine',
    'Nephrology',
    'Neuromedicine',
    'Neurology',
    'Medicine',
    'Brain',
    'Nerve',
    'Headache',
    'Migraine',
    'Stroke',
];

export { specializations };
